---
- name: install yum packages
  yum:
    name:
      - tmux
    state: latest

- name: symlink nvim to sys path as nvim and vim
  file:
    src: ~phantom/.local/bin/nvim
    dest: "{{ item }}"
    state: link
    force: yes
  loop:
    - /usr/bin/nvim
    - /usr/bin/vim
